---
editor_options: 
  markdown: 
    wrap: 72
---

# Principales hallazgos longitudinales

## Nota Explicativa

A continuación, se presentan los principales resultados de la encuesta ELSOC elaborados por investigadores del Centro de Conflicto y Cohesión Social (COES). Dada la diversidad de temas que son abordados en la encuesta, los investigadores colaboradores utilizaron diversos enfoques teóricos y herramientas empíricas en su análisis. Sin embargo, en Radiografía del Cambio Social se han definido una serie de criterios comunes para el desarrollo de resultados empíricos:

- Foco en la evolución y cambio en las actitudes de la población, aún cuando en ocasiones se analizan preguntas incluidas en una o dos olas del estudio. 
- Uso de pruebas estadísticas específicas para el análisis longitudinal. 
- Utilización de submuestra de 2.096 participantes del estudio presentes en las cuatro mediciones (2016, 2017, 2018 y 2019). 
- Tamaños muestrales reportados menores se explican exclusivamente por no respuesta a ítemes específicos. 
- Utilización del diseño muestral complejo (ponderador muestral ajustado a población regional y sexo, estrato y conglomerado muestral) en el desarrollo de figuras descriptivas y pruebas inferenciales. 


## Levantamiento durante estallido social

El año 2019 correspondía levantar la cuarta ola de la Muestra 1 y la segunda ola de la Muestra 2 de ELSOC. El trabajo de terreno estaba programado para iniciarse el sábado 19 de Octubre de 2019, pero debido al estallido social ocurrido el 18 de Octubre, este debió ser suspendido hasta el jueves 21 de noviembre. El trabajo de terreno culminó el 9 de marzo del 2020.

Ante la intensificación de la protesta social, comienza una coyuntura histórica inédita que pone de relieve importantes desafíos políticos y sociales para Chile, y su democracia. En este contexto, COES toma la decisión de incluir una serie de baterías y preguntas específicamente diseñadas para comprender mejor como la opinión pública chilena percibió y experimentó el estallido social, y de esta manera, poder contribuir a un entendimiento más profundo de nuestra sociedad tomando en consideración este periodo de nuestra historia reciente.

